services:
  cv-parser:
    build:
      context: ./cv-parser
      dockerfile: Dockerfile
    ports:
      - "5051:5051"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - ./temp:/app/temp
    restart: unless-stopped

  job-parser:
    build:
      context: ./job-parser
      dockerfile: Dockerfile
    ports:
      - "5053:5053"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - ./temp:/app/temp
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
