# 🐳 SuperSmartMatch V2 - Configuration Docker avec API Avancée
version: '3.8'

services:
  # Services existants V2
  cv-parser-v2-enriched:
    build: ./cv-parser-v2
    ports:
      - "5051:5051"
    environment:
      - PARSER_VERSION=enriched_v2
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5051/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  job-parser-v2-enriched:
    build: ./job-parser-v2
    ports:
      - "5053:5053"
    environment:
      - PARSER_VERSION=enriched_v2
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5053/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # NOUVEAU : API Matching Avancée
  matching-api:
    build:
      context: .
      dockerfile: Dockerfile.matching-api
    ports:
      - "5055:5055"
    environment:
      - CV_PARSER_URL=http://cv-parser-v2-enriched:5051
      - JOB_PARSER_URL=http://job-parser-v2-enriched:5053
      - FLASK_ENV=production
      - FLASK_APP=api-matching-advanced.py
    depends_on:
      - cv-parser-v2-enriched
      - job-parser-v2-enriched
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5055/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Interface Web avec Nginx
  web-interface:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./web-interface:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - matching-api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local

networks:
  default:
    driver: bridge