# SuperSmartMatch V2 - Development Configuration
# Optimized for development and testing with detailed logging and debugging

# Core Settings
version: "2.0.0-dev"
environment: "development"
debug: true

# Feature Flags for Development
feature_flags:
  enable_v2: true
  v2_traffic_percentage: 100  # Full V2 in development
  enable_nexten_algorithm: true
  enable_smart_selection: true
  enable_questionnaire_matching: true
  enable_performance_monitoring: true
  enable_ab_testing: true  # Enable for testing
  enable_fallback_chaining: true
  enable_cache_warming: false

# Algorithm Configuration (Relaxed timeouts for debugging)
algorithms:
  nexten:
    enabled: true
    weight: 1.3
    timeout_ms: 200  # Relaxed for debugging
    cache_enabled: false  # Disable for testing
    cache_ttl_seconds: 60
    max_parallel_requests: 4
    fallback_enabled: true
    custom_parameters:
      enable_questionnaire_weighting: true
      confidence_threshold: 0.6  # Lower for more results
      batch_processing_size: 5
  
  smart:
    enabled: true
    weight: 1.0
    timeout_ms: 150
    cache_enabled: false
    cache_ttl_seconds: 60
    max_parallel_requests: 4
    fallback_enabled: true
    custom_parameters:
      enable_geographical_optimization: true
      max_distance_calculation_km: 200  # Larger for testing
  
  enhanced:
    enabled: true
    weight: 1.1
    timeout_ms: 120
    cache_enabled: false
    cache_ttl_seconds: 60
    max_parallel_requests: 4
    fallback_enabled: true
    custom_parameters:
      adaptive_weighting: true
      senior_experience_boost: 1.1
  
  semantic:
    enabled: true
    weight: 0.9
    timeout_ms: 180
    cache_enabled: false
    cache_ttl_seconds: 60
    max_parallel_requests: 2
    fallback_enabled: true
    custom_parameters:
      nlp_model: "bert-base-uncased"
      semantic_similarity_threshold: 0.65  # Lower for more matches
  
  hybrid:
    enabled: true
    weight: 1.2
    timeout_ms: 250
    cache_enabled: false
    cache_ttl_seconds: 60
    max_parallel_requests: 2
    fallback_enabled: true
    custom_parameters:
      consensus_threshold: 0.7  # Lower for testing
      multi_algorithm_validation: true

# Selection Rules (More permissive for testing)
selection:
  min_skills_for_nexten: 3  # Lower for easier testing
  min_questionnaire_completeness: 0.5
  min_company_questionnaire_completeness: 0.3
  
  senior_experience_threshold: 5
  partial_questionnaire_threshold: 0.2
  
  max_distance_km: 100
  mobility_complexity_threshold: 2
  
  semantic_skill_description_length: 50
  semantic_complexity_threshold: 0.6
  
  critical_positions:
    - "CEO"
    - "CTO"
    - "Manager"
    - "Senior"
  
  high_value_clients: ["test-client"]

# Performance Settings (Relaxed for development)
performance:
  max_response_time_ms: 500  # Relaxed for debugging
  cache_enabled: false  # Disable for fresh results
  cache_size: 100
  cache_ttl_seconds: 60
  
  # Detailed Monitoring for Development
  enable_detailed_logging: true
  metrics_retention_hours: 2  # Shorter retention
  enable_ab_testing: true
  
  # Alert Thresholds (Relaxed)
  error_rate_warning: 0.10     # 10% error rate warning
  error_rate_critical: 0.20    # 20% error rate critical
  response_time_warning_ms: 300
  response_time_critical_ms: 500
  success_rate_threshold: 0.80

# Nexten Configuration (Development optimized)
nexten:
  enabled: true
  timeout_ms: 200
  cache_enabled: false
  parallel_processing: false  # Easier debugging
  max_workers: 2
  
  model_version: "latest"
  confidence_threshold: 0.6
  enable_questionnaire_weighting: true
  
  enable_skill_caching: false
  enable_embedding_cache: false
  batch_processing_size: 3
  
  fallback_to_enhanced: true
  emergency_timeout_ms: 100

# External Services (Local/Mock)
database_url: "sqlite:///dev_supersmartmatch.db"
redis_url: null  # Use in-memory cache
monitoring_endpoint: null

# Security (Relaxed for development)
api_key_required: false
rate_limit_requests_per_minute: 10000  # No limiting in dev
max_request_size_mb: 50

# Logging Configuration (Verbose for development)
logging:
  level: "DEBUG"
  format: "text"  # Easier to read in development
  include_request_id: true
  include_user_id: true
  performance_logging: true
  algorithm_debug_logging: true
