# SuperSmartMatch V2 Configuration
# Production-ready configuration for unified intelligent matching service

version: "2.0.0"
environment: "production"
port: 5070
host: "0.0.0.0"

# Service Configuration
service:
  name: "SuperSmartMatch V2"
  description: "Unified Intelligent Matching Service"
  max_response_time_ms: 100
  enable_cors: true
  enable_gzip: true

# Feature Flags
feature_flags:
  enable_v2: true
  v2_traffic_percentage: 100
  enable_nexten_algorithm: true
  enable_smart_selection: true
  enable_ab_testing: true
  enable_performance_monitoring: true

# External Services Configuration
external_services:
  nexten_matcher:
    enabled: true
    base_url: "http://localhost:5052"
    timeout_ms: 3000
    retry_attempts: 2
    circuit_breaker:
      failure_threshold: 3
      recovery_timeout_s: 30
  
  v1_algorithms:
    enabled: true
    base_url: "http://localhost:5062" 
    timeout_ms: 2000
    retry_attempts: 3
    circuit_breaker:
      failure_threshold: 5
      recovery_timeout_s: 60

# Algorithm Configuration
algorithms:
  nexten:
    enabled: true
    priority: 1
    timeout_ms: 3000
    cache_ttl_s: 600
    confidence_threshold: 0.85
    
  smart:
    enabled: true
    priority: 2
    timeout_ms: 1500
    cache_ttl_s: 3600
    confidence_threshold: 0.75
    
  enhanced:
    enabled: true
    priority: 3
    timeout_ms: 2000
    cache_ttl_s: 1800
    confidence_threshold: 0.70
    
  semantic:
    enabled: true
    priority: 4
    timeout_ms: 2500
    cache_ttl_s: 1200
    confidence_threshold: 0.68
    
  hybrid:
    enabled: true
    priority: 5
    timeout_ms: 4000
    cache_ttl_s: 900
    confidence_threshold: 0.80

# Algorithm Selection Rules
selection_rules:
  # Complete questionnaire data - use Nexten for maximum ML precision
  complete_data_threshold:
    questionnaire_completeness: 0.8
    cv_completeness: 0.7
    requires_company_questionnaires: true
    selected_algorithm: "nexten"
    
  # Geographic constraints - use Smart Match for location optimization  
  location_constraints:
    has_location_data: true
    selected_algorithm: "smart"
    
  # Senior profiles - use Enhanced for experience weighting
  senior_profile:
    experience_level: "senior"
    cv_completeness: 0.6
    selected_algorithm: "enhanced"
    
  # Complex skills - use Semantic for NLP analysis
  complex_skills:
    skills_complexity_threshold: 0.6
    selected_algorithm: "semantic"
    
  # Medium data completeness - use Hybrid for consensus
  medium_completeness:
    min_questionnaire_completeness: 0.5
    min_cv_completeness: 0.5
    selected_algorithm: "hybrid"
    
  # Default fallback - use Nexten for best overall performance
  default:
    selected_algorithm: "nexten"

# Performance Configuration
performance:
  max_concurrent_requests: 1000
  request_timeout_ms: 10000
  enable_caching: true
  cache_backend: "redis"
  
  # Rate limiting
  rate_limiting:
    enabled: true
    requests_per_minute: 1000
    burst_limit: 100

# Caching Configuration
cache:
  redis:
    host: "localhost"
    port: 6379
    db: 0
    password: null
    connection_pool_size: 20
    max_connections: 100
    
  ttl_defaults:
    nexten_results: 600
    smart_results: 3600
    enhanced_results: 1800
    semantic_results: 1200
    hybrid_results: 900

# Monitoring and Health Checks
monitoring:
  health_check_interval_s: 30
  performance_metrics:
    enabled: true
    collection_interval_s: 60
    retention_days: 30
    
  alerts:
    response_time_threshold_ms: 150
    error_rate_threshold: 0.05
    circuit_breaker_open_alert: true

# Logging Configuration
logging:
  level: "INFO"
  format: "json"
  enable_access_logs: true
  enable_performance_logs: true
  
  files:
    application: "/var/log/supersmartmatch-v2/app.log"
    access: "/var/log/supersmartmatch-v2/access.log"
    performance: "/var/log/supersmartmatch-v2/performance.log"

# Security Configuration
security:
  enable_api_key_auth: false
  cors:
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "OPTIONS"]
    allow_headers: ["*"]
    allow_credentials: true
    
  request_validation:
    max_payload_size_mb: 10
    enable_input_sanitization: true

# Development Configuration (overrides for development environment)
development:
  port: 5070
  debug: true
  hot_reload: true
  enable_detailed_errors: true
  logging:
    level: "DEBUG"
  external_services:
    nexten_matcher:
      base_url: "http://localhost:5052"
    v1_algorithms:
      base_url: "http://localhost:5062"

# Testing Configuration (overrides for testing environment)
testing:
  port: 5071
  enable_mock_services: true
  external_services:
    nexten_matcher:
      base_url: "http://localhost:5053"  # Mock service
    v1_algorithms:
      base_url: "http://localhost:5063"  # Mock service
