groups:
  - name: supersmartmatch_alerts
    rules:
      # Service availability alerts
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute."

      # High error rate alerts
      - alert: HighErrorRate
        expr: rate(http_requests_total{status_code!~"2.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate on {{ $labels.job }}"
          description: "Error rate is {{ $value | humanizePercentage }} for service {{ $labels.job }}."

      # High response time alerts
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time on {{ $labels.job }}"
          description: "95th percentile response time is {{ $value }}s for service {{ $labels.job }}."

      # Critical response time alerts
      - alert: CriticalResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.2
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Critical response time on {{ $labels.job }}"
          description: "95th percentile response time is {{ $value }}s for service {{ $labels.job }}."

      # Low precision matching alerts
      - alert: LowMatchingPrecision
        expr: matching_precision_percent < 90
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low matching precision"
          description: "Matching precision is {{ $value }}% which is below 90% threshold."

      # Critical precision alerts
      - alert: CriticalMatchingPrecision
        expr: matching_precision_percent < 85
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Critical matching precision"
          description: "Matching precision is {{ $value }}% which is critically low."

      # High memory usage alerts
      - alert: HighMemoryUsage
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.container_label_com_docker_compose_service }}"
          description: "Memory usage is {{ $value }}% on container {{ $labels.container_label_com_docker_compose_service }}."

      # High CPU usage alerts
      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.container_label_com_docker_compose_service }}"
          description: "CPU usage is {{ $value }}% on container {{ $labels.container_label_com_docker_compose_service }}."
