global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'supersmartmatch-v1'
    static_configs:
      - targets: ['supersmartmatch-v1:5062']
    labels:
      service: 'supersmartmatch'
      version: 'v1'

  - job_name: 'supersmartmatch-v2'
    static_configs:
      - targets: ['supersmartmatch-v2:5070']
    labels:
      service: 'supersmartmatch'
      version: 'v2'

  - job_name: 'nexten-matcher'
    static_configs:
      - targets: ['nexten-matcher:5052']
    labels:
      service: 'nexten-matcher'

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    labels:
      service: 'nginx'
