global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # SuperSmartMatch V1 Service
  - job_name: 'supersmartmatch-v1'
    static_configs:
      - targets: ['supersmartmatch-v1:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # SuperSmartMatch V2 Service (Orchestrator)
  - job_name: 'supersmartmatch-v2'
    static_configs:
      - targets: ['supersmartmatch-v2:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nexten Advanced Matcher
  - job_name: 'nexten-matcher'
    static_configs:
      - targets: ['nexten-matcher:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis Monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Grafana Monitoring
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 60s
    metrics_path: '/metrics'
