# Configuration Prometheus corrigée pour le monitoring du projet Commitment
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'nexten-cluster'
    replica: 'prometheus-01'

# Règles d'alerte
rule_files:
  - "rules/*.yml"

# Configuration AlertManager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Découverte et collection des métriques
scrape_configs:
  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Métriques système (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Métriques conteneurs Docker (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Métriques Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Métriques PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # API Backend principal
  - job_name: 'api-backend'
    static_configs:
      - targets: ['api:5000']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Service parsing CV
  - job_name: 'cv-parser'
    static_configs:
      - targets: ['cv-parser:5000']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Service parsing jobs
  - job_name: 'job-parser'
    static_configs:
      - targets: ['job-parser:5000']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Service matching
  - job_name: 'matching-api'
    static_configs:
      - targets: ['matching-api:5000']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Adaptateur de données
  - job_name: 'data-adapter'
    static_configs:
      - targets: ['data-adapter:5053']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # MinIO (stockage)
  - job_name: 'minio'
    static_configs:
      - targets: ['storage:9000']
    scrape_interval: 30s
    metrics_path: '/minio/v2/metrics/cluster'