global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:5050']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'microservices'
    static_configs:
      - targets: 
          - 'cv-parser-service:5051'
          - 'job-parser-service:5053'
          - 'matching-service:5052'
          - 'user-service:5054'
          - 'notification-service:5055'
          - 'analytics-service:5056'
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'infrastructure'
    static_configs:
      - targets:
          - 'postgres:5432'
          - 'redis:6379'
          - 'minio:9000'
    scrape_interval: 60s
