# Configuration automatique des sources de données Grafana
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
    secureJsonData: {}

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    orgId: 1
    url: http://elasticsearch:9200
    database: "logstash-*"
    basicAuth: false
    version: 1
    editable: true
    jsonData:
      esVersion: 8
      timeField: "@timestamp"
      maxConcurrentShardRequests: 5
      logMessageField: "message"
      logLevelField: "level"