# Configuration automatique des datasources Grafana
apiVersion: 1

# Liste des datasources
datasources:
  # Prometheus principal
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      tlsSkipVerify: true
    version: 1

  # Prometheus pour les métriques temps réel
  - name: Prometheus-Realtime
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "30s"
      tlsSkipVerify: true
    version: 1