apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 30s
      queryTimeout: 60s
      httpMethod: POST
    secureJsonData: {}

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis:6379
    editable: true
    jsonData:
      client: standalone
    secureJsonData: {}
