name: 🚀 Force Pages Deploy - Ultra v6.1

on:
  push:
    branches: [ main ]
    paths: [ 'templates/candidate-upload.html' ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔥 Clear Cache Headers
        run: |
          echo "Force deploying ULTRA PARSING v6.1..."
          echo "Timestamp: $(date)"
          echo "SHA: ${{ github.sha }}"
          
          # Ajouter un timestamp unique au fichier
          sed -i 's/2025-06-23T13:30:00Z/'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'/g' templates/candidate-upload.html
          
      - name: 📦 Setup Pages
        uses: actions/configure-pages@v4

      - name: 📤 Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
